Mounting the Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Importing all the necessary libraries

In [ ]:
# import all the necessary libraries here
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, accuracy_score, recall_score
from sklearn.preprocessing import StandardScaler

Readin the data from the CSV File

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/asssign2/dataset/cross-validation.csv')
print(df.shape)

(614, 13)


Visualisation of the data

In [ ]:
df.tail(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
604            12000                0.0       496.0             360.0   
605             2400             3800.0         NaN             180.0   
606             3400             2500.0       173.0             360.0   
607             3987             1411.0       157.0             360.0   
608             3232             1950.0       108.0             360.0   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
604             1.0     Semiurban           Y  
605             1.0         Urban           N  
606             1.0     Semiurban           Y  
607             1.0         Rural           Y  
608             1.0         Rural           Y  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

Splitting the data into features and target labels

In [ ]:
x_train=np.array(df.iloc[:,1:12])
y_train=np.array(df.iloc[:,12])

In [ ]:
x_train.shape

(614, 11)

In [ ]:
x_train

array([['Male', 'No', '0', ..., 360.0, 1.0, 'Urban'],
       ['Male', 'Yes', '1', ..., 360.0, 1.0, 'Rural'],
       ['Male', 'Yes', '0', ..., 360.0, 1.0, 'Urban'],
       ...,
       ['Male', 'Yes', '1', ..., 360.0, 1.0, 'Urban'],
       ['Male', 'Yes', '2', ..., 360.0, 1.0, 'Urban'],
       ['Female', 'No', '0', ..., 360.0, 0.0, 'Semiurban']], dtype=object)

In [ ]:
y_train.shape

(614,)

In [ ]:
y_train

array(['Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N

Encoding all the features which needs to be encoded for traing the model

In [ ]:
for i in range(x_train.shape[0]):
  if x_train[i][0]=='Male':
    x_train[i][0]=0
  if x_train[i][0]=='Female':
     x_train[i][0]=1
  if x_train[i][1]=='Yes':
     x_train[i][1]=1
  if x_train[i][1]=='No':
     x_train[i][1]=0
  if x_train[i][2]=='0':
     x_train[i][2]=1
  if x_train[i][2]=='1':
     x_train[i][2]=1
  if x_train[i][2]=='2':
     x_train[i][2]=2
  if x_train[i][2]=='3+':
     x_train[i][2]=3
  if x_train[i][3]=='Graduate':
     x_train[i][3]=0
  if x_train[i][3]=='Not Graduate':
     x_train[i][3]=1
  if x_train[i][4]=='Yes':
     x_train[i][4]=1
  if x_train[i][4]=='No':
     x_train[i][4]=0
  if x_train[i][10]=='Urban':
     x_train[i][10]=0
  if x_train[i][10]=='Semiurban':
     x_train[i][10]=1
  if x_train[i][10]=='Rural':
     x_train[i][10]=2

Visualising the Data After encoding of the required features

In [ ]:
x_train

array([[0, 0, 1, ..., 360.0, 1.0, 1],
       [0, 1, 1, ..., 360.0, 1.0, 3],
       [0, 1, 1, ..., 360.0, 1.0, 1],
       ...,
       [0, 1, 1, ..., 360.0, 1.0, 1],
       [0, 1, 2, ..., 360.0, 1.0, 1],
       [1, 0, 1, ..., 360.0, 0.0, 2]], dtype=object)

One Hot Encoding the target labels

In [ ]:
y_train = np.array([1 if label == 'Y' else 0 for label in y_train])
y_train

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

Normalising the continous features present in training data

In [ ]:
selected_feature_indices = [5, 6, 7, 8]
scaler = StandardScaler()
x_train[:, selected_feature_indices] = np.array(scaler.fit_transform(x_train[:, selected_feature_indices]))
x_train = x_train.astype(np.float16)
x_train = np.nan_to_num(x_train, nan=0.0)

In [ ]:
x_train[0]

array([ 0.    ,  0.    ,  1.    ,  0.    ,  0.    ,  0.073 , -0.5547,
        0.    ,  0.2766,  1.    ,  1.    ], dtype=float16)



*   Initialising the logistic regression model from sklearn with 'saga' solver and no regularising penalty with a maximum iterations of 5000.
*   initialising all the lists and necessary variables for 5 fold  cross validation strategy
*   Implemented Cross validation by splitting data at random indices and calculated the required metrics
*  finally calcualted the mean precison,mean accuracy and mean recall after cross validation









In [ ]:
model = LogisticRegression(solver='saga', penalty=None, max_iter=5000)

n_folds = 5
validation_percentage = 0.2
m = x_train.shape[0]
prec_score_list=[]
acc_score_list=[]
rec_score_list=[]
num_validation_samples = int(m * validation_percentage)


indices = np.arange(m)
np.random.shuffle(indices)
fold_size = m // n_folds
folds = [indices[i:i+fold_size] for i in range(0, m, fold_size)]


for fold_number in range(n_folds):
    validation_indices = folds[fold_number]
    training_indices = np.concatenate([f for i, f in enumerate(folds) if i != fold_number])

    X_train, Y_train = x_train[training_indices], y_train[training_indices]
    X_valid, Y_valid = x_train[validation_indices], y_train[validation_indices]

    model.fit(X_train, Y_train)
    Y_pred = model.predict(X_valid)
    prec_score = precision_score(Y_valid, Y_pred)
    acc_score = accuracy_score(Y_valid, Y_pred)
    rec_score = recall_score(Y_valid, Y_pred)
    prec_score_list.append(prec_score)
    acc_score_list.append(acc_score)
    rec_score_list.append(rec_score)
    print("fold:", fold_number + 1, "prec_score:", prec_score, "acc_score:", acc_score, "rec_score:", rec_score)

prec_score = sum(prec_score_list) / n_folds
acc_score = sum(acc_score_list) / n_folds
rec_score = sum(rec_score_list) / n_folds
print("mean precision:", prec_score)
print("mean acc_score:", acc_score)
print("mean rec_score:", rec_score)


fold: 1 prec_score: 0.8229166666666666 acc_score: 0.7868852459016393 rec_score: 0.8977272727272727
fold: 2 prec_score: 0.8315789473684211 acc_score: 0.8114754098360656 rec_score: 0.9186046511627907
fold: 3 prec_score: 0.7802197802197802 acc_score: 0.7540983606557377 rec_score: 0.8765432098765432
fold: 4 prec_score: 0.7373737373737373 acc_score: 0.7295081967213115 rec_score: 0.9125
fold: 5 prec_score: 0.8089887640449438 acc_score: 0.7622950819672131 rec_score: 0.8571428571428571
mean precision: 0.7962155791347099
mean acc_score: 0.7688524590163934
mean rec_score: 0.8925035981818927
